fields.c File Reference
contains driving functions for the global fields
#include <stdio.h>
*
#include <stdlib.h>
*
#include <math.h>
*
#include `global.h`
*
#include `fields.h`
*
Functions
void fieldsInit ()
void fieldsSolve ()
Detailed Description
contains driving functions for the global fields
Definition in file fields.c.
Function Documentation
void fieldsInit ()
This function intializes the fields. Various parameters are set and the Hypre initialization of the system is executed.
Definition at line 45 of file fields.c.
References chemEnvInitBC(), chemEnvInitSolver(), chemEnvInitSystem(), chemField, densityField, fieldAddr, fieldBC, fieldCriticalLevel1, fieldCriticalLevel2, fieldDiffCoef, fieldDt, fieldICMean, fieldICVar, fieldName, fieldType, gfDt, gfields, glucose, gridSize, hydrogenIon, NCHEM, oxygen, SCALAR_FIELD, secondsPerStep, tempEnvInitBC(), tempEnvInitSolver(), tempEnvInitSystem(), temperature, tempField, int64Vector3d::x, int64Vector3d::y, and int64Vector3d::z.
{
  int nf, i;
  int chf;
  if (!gfields)
    return;
  nf = 0;
  strcpy(fieldName[nf], "density");
  fieldType[nf] = SCALAR_FIELD;
  fieldAddr[nf] =
      (double *) calloc(gridSize.x * gridSize.y * gridSize.
      z,
            sizeof(double));
  densityField = (double *) fieldAddr[nf];
  for (i = 0; i < gridSize.x * gridSize.y * gridSize.z; i++)
    densityField[i] = 0.0;
  nf++;
  strcpy(fieldName[nf], "temp");
  fieldType[nf] = SCALAR_FIELD;
  fieldAddr[nf] =
      (double *) calloc(gridSize.x * gridSize.y * gridSize.
      z,
            sizeof(double));
  tempField = (double *) fieldAddr[nf];
  for (i = 0; i < gridSize.x * gridSize.y * gridSize.z; i++)
    tempField[i] = 0.0;
  fieldDiffCoef[nf] = 1 * 1e-5;
  fieldBC[nf] = 42.0;
  fieldICMean[nf] = 36.0;
  fieldICVar[nf] = 0;
  nf++;
  /* set default values for chemical parameters */
  for (chf = 0; chf < NCHEM; chf++) {
    if (chf == 0) {
      strcpy(fieldName[nf], "oxygen");
      fieldDt[nf] = gfDt;
      fieldCriticalLevel1[nf] *= gfDt; //*(boxVolume/cellVolume);
      fieldCriticalLevel2[nf] *= gfDt; //*(boxVolume/cellVolume);
    }
    if (chf == 1) {
      strcpy(fieldName[nf], "glucose");
      fieldDt[nf] = secondsPerStep;
    }
    if (chf == 2) {
      strcpy(fieldName[nf], "hydrogenIon");
      fieldDt[nf] = secondsPerStep;
    }
    fieldType[nf] = SCALAR_FIELD;
    fieldAddr[nf] =
    (double *) calloc(gridSize.x * gridSize.y * gridSize.
      z,
              sizeof(double));
    chemField[chf] = (double *) fieldAddr[nf];
    for (i = 0; i < gridSize.x * gridSize.y * gridSize.
      z; i++)
      chemField[chf][i] = 0.0;
    nf++;
  }
  /* initialize temperature field */
  if (temperature) {
    tempEnvInitSystem();
    tempEnvInitBC();
    tempEnvInitSolver();
  }
  /* initialize chemical fields */
  for (i = 0; i < NCHEM; i++) {
    if (i == 0 && !oxygen)
      continue;
    if (i == 1 && !glucose)
      continue;
    if (i == 2 && !hydrogenIon)
      continue;
    chemEnvInitSystem(i);
    chemEnvInitBC(i);
    chemEnvInitSolver(i);
  }
}
void fieldsSolve ()
This is a driving function for global field solver. It is called in each step of the simulation.
Definition at line 131 of file fields.c.
References chemEnvSolve(), gfields, gfIter, gfIterPerStep, glucose, hydrogenIon, NCHEM, oxygen, tempEnvSolve(), temperature, and updateCellStates().
{
  int i;
  if (!gfields)
    return;
  for (gfIter = 0; gfIter < gfIterPerStep; gfIter++) {
    /* update cell state (if more than one iteration) */
    if (gfIter > 0)
      updateCellStates();
    /* solve temperature field */
    if (temperature)
      tempEnvSolve();
    /* solve chemical fields */
    for (i = 0; i < NCHEM; i++) {
      if (i == 0 && !oxygen)
    continue;
      if (i == 1 && !glucose)
    continue;
      if (i == 2 && !hydrogenIon)
    continue;
      chemEnvSolve(i);
    }
  }
}