stats.c File Reference
contains functions computing and printing simulation statisctical information
#include <stdio.h>
*
#include <stdlib.h>
*
#include <mpi.h>
*
#include <math.h>
*
#include <inttypes.h>
*
#include `global.h`
*
Functions
void statisticsDensity ()
void statisticsDistance ()
void statisticsVelocity ()
void statisticsSize ()
void statisticsPhases ()
void statisticsPrint ()
Detailed Description
contains functions computing and printing simulation statisctical information
Definition in file stats.c.
Function Documentation
void statisticsDensity ()
This function computes and prints out density statistics.
Definition at line 38 of file stats.c.
References cells, statisticsData::densavg, statisticsData::densdev, cellData::density, lnc, statisticsData::maxdens, statisticsData::mindens, MPIrank, nc, and statistics.
{
  int c;
  double sum = 0.0, mean;
  double globalMaxDens;
  double globalMinDens;
  double deviation;
  statistics.maxdens = 0;
  statistics.mindens = 1024;
  for (c = 0; c < lnc; c++) {
    sum += cells[c].density;
    statistics.maxdens =
    (cells[c].density >
     statistics.maxdens ? cells[c].density :
      statistics.maxdens);
    statistics.mindens =
    (cells[c].density <
     statistics.mindens ? cells[c].density :
      statistics.mindens);
  }
  MPI_Allreduce(&sum, &mean, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);
  MPI_Allreduce(&statistics.maxdens, &globalMaxDens, 1, MPI_DOUBLE,
        MPI_MAX, MPI_COMM_WORLD);
  MPI_Allreduce(&statistics.mindens, &globalMinDens, 1, MPI_DOUBLE,
        MPI_MIN, MPI_COMM_WORLD);
  statistics.maxdens = globalMaxDens;
  statistics.mindens = globalMinDens;
  mean /= nc;
  statistics.densavg = mean;
  sum = 0.0;
  for (c = 0; c < lnc; c++)
    sum += (cells[c].density - mean) * (cells[c].density - mean);
  MPI_Allreduce(&sum, &(statistics.densdev), 1, MPI_DOUBLE, MPI_SUM,
        MPI_COMM_WORLD);
  statistics.densdev /= nc;
  statistics.densdev = sqrt(statistics.densdev);
  if (MPIrank == 0)
    printf("%12s%10.4lf%10.4lf%10.4lf%10.4lf\n", "Density ",
       globalMinDens, globalMaxDens, mean, statistics.densdev);
}
void statisticsDistance ()
This function computes and prints out distance statistics.
Definition at line 88 of file stats.c.
References statisticsData::mindist, MPIrank, and statistics.
{
  double globalMinDist;
  double globalMaxDist;
  MPI_Allreduce(&statistics.mindist, &globalMinDist, 1, MPI_DOUBLE,
        MPI_MIN, MPI_COMM_WORLD);
  statistics.mindist = globalMinDist;
  if (MPIrank == 0)
    printf("%12s%10.4lf%10s%10s%10s\n", "Distance ", globalMinDist, "-",
       "-", "-");
}
void statisticsPhases ()
This function computes and prints out phases statistics.
Definition at line 137 of file stats.c.
References cnc, g0nc, g1nc, g2nc, mnc, MPIrank, nc, nnc, and snc.
{
  if (MPIrank == 0) {
    printf("%12s%12s%12s%12s%12s%12s\n", "Cell phase ", "G0", "G1", "S",
       "G2", "M");
    printf("%12s%12" PRId64 "%12" PRId64 "%12" PRId64 "%12" PRId64 "%12"
       PRId64 "\n", "N. of cells", g0nc, g1nc, snc, g2nc, mnc);
    printf("\n%16s%12" PRId64 "\n", "Healthy cells ", nc - cnc - nnc);
    printf("%16s%12" PRId64 "\n", "Cancer cells ", cnc);
    printf("%16s%12" PRId64 "\n", "Necrotic cells ", nnc);
  }
}
void statisticsPrint ()
This is a driving function for computing and printing out statistics.
Definition at line 153 of file stats.c.
References MPIrank, statisticsDensity(), statisticsDistance(), statisticsPhases(), and statisticsSize().
{
  if (MPIrank == 0)
    printf("%12s%10s%10s%10s%10s\n", "", "Min", "Max", "Avg", "Dev");
  statisticsDensity();
  statisticsDistance();
  /*statisticsVelocity(); */
  statisticsSize();
  if (MPIrank == 0)
    printf("\n");
  statisticsPhases();
}
void statisticsSize ()
This function computes and prints out cell size statistics.
Definition at line 120 of file stats.c.
References statisticsData::maxsize, statisticsData::minsize, MPIrank, and statistics.
{
  double globalMaxSize, globalMinSize;
  MPI_Reduce(&statistics.maxsize, &globalMaxSize, 1, MPI_DOUBLE, MPI_MAX,
         0, MPI_COMM_WORLD);
  MPI_Reduce(&statistics.minsize, &globalMinSize, 1, MPI_DOUBLE, MPI_MIN,
         0, MPI_COMM_WORLD);
  if (MPIrank == 0)
    printf("%12s%10.4lf%10.4lf%10s%10s\n", "Size ", globalMinSize,
       globalMaxSize, "-", "-");
}
void statisticsVelocity ()
This function computes and prints out velocity statistics.
Definition at line 106 of file stats.c.
References globalMaxVel, globalMinVel, statisticsData::maxvel, statisticsData::minvel, MPIrank, and statistics.
{
  MPI_Reduce(&statistics.minvel, &globalMinVel, 1, MPI_DOUBLE, MPI_MIN, 0,
         MPI_COMM_WORLD);
  MPI_Reduce(&statistics.maxvel, &globalMaxVel, 1, MPI_DOUBLE, MPI_MAX, 0,
         MPI_COMM_WORLD);
  if (MPIrank == 0)
    printf("%12s%10.4lf%10.4lf%10s%10s\n", "Velocity ", globalMinVel,
       globalMaxVel, "-", "-");
}